#title: "BFT-AI 2025"
#description: "1st Workshop on Byzantine Fault Tolerance and Artificial Intelligence Systems"
#url: "https://bft-ai-2025.github.io"
##baseurl: ""
#repository: bft-ai-2025/bft-ai2025.
#
##theme: minimal-mistakes-jekyll
#remote_theme: "mmistakes/minimal-mistakes"
#plugins:
#  - jekyll-include-cache
#  - jekyll-remote-theme
#  - jekyll-include-cache
#
#
#markdown: kramdown
#kramdown:
#  math_engine: mathjax
#
#include:
#  - _pages
title: "BFT-AI 2025"
description: "1st Workshop on Byzantine Fault Tolerance and Artificial Intelligence Systems"
url: "https://bft-ai-2025.github.io"
baseurl: ""  # Important: leave this empty for user/organization sites

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
kramdown:
  math_engine: mathjax

include:
  - _pages

repository: bft-ai-2025/bft-ai-2025.github.io

